# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import Calculator_pb2 as Calculator__pb2


class CalculatorStub(object):
  """The service definition
  """

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.Add = channel.unary_unary(
        '/Calculator/Add',
        request_serializer=Calculator__pb2.Numbers.SerializeToString,
        response_deserializer=Calculator__pb2.Result.FromString,
        )


class CalculatorServicer(object):
  """The service definition
  """

  def Add(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_CalculatorServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'Add': grpc.unary_unary_rpc_method_handler(
          servicer.Add,
          request_deserializer=Calculator__pb2.Numbers.FromString,
          response_serializer=Calculator__pb2.Result.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'Calculator', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
